branches:
  only:
    - /^v(\d+\.)+\d+$/
    - master

os: Visual Studio 2015

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain stable --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

cache:
  - '%USERPROFILE%\.cargo'
  - target

build_script:
  - cargo build --release

after_build:
  - 7z a win32.zip %APPVEYOR_BUILD_FOLDER%\target\release\sp.exe

test_script:
  - cargo test

artifacts:
  - path: win32.zip
    name: sp

deploy:
  provider: GitHub
  auth_token: $(GITHUB_AUTH_TOKEN)
  artifact: sp
  force_update: true