[package]
name = "spawner_opts_derive"
version = "0.0.0"
authors = ["ptslog <hsfk@yandex.ru>"]

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.3"
syn = "0.15.22"