[package]
name = "sp"
version = "0.0.0"
authors = ["ptslog <hsfk@yandex.ru>"]

[[bin]]
name = "sp"
path = "main.rs"

[dependencies]
sp_derive = { path = "../sp_derive" }
spawner = { path = "../libspawner" }